import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

import '../../core/config/app_config.dart';

Future<void> maybeInitializeFirebase() async {
  if (!AppConfig.firebaseEnabled) return;

  try {
    // Try to use firebase_options.dart if available (generated by flutterfire configure)
    // Uncomment the following lines after running `flutterfire configure`:
    //
    // import 'firebase_options.dart';
    // await Firebase.initializeApp(
    //   options: DefaultFirebaseOptions.currentPlatform,
    // );
    
    // Default initialization (works for Android/iOS/macOS/Windows/Linux
    // after adding platform config files manually)
    await Firebase.initializeApp();
  } catch (e, st) {
    // Keep the app runnable even before Firebase config is added.
    debugPrint('Firebase init failed (FIREBASE_ENABLED=true): $e');
    debugPrintStack(stackTrace: st);
  }
}

