// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlY5up6xTAdoEgYVk_vfBKwLteTQ8d7Jo',
    appId: '1:651530704617:web:a7f452f008a0911abc4278',
    messagingSenderId: '651530704617',
    projectId: 'mikrotaps',
    authDomain: 'mikrotaps.firebaseapp.com',
    storageBucket: 'mikrotaps.firebasestorage.app',
    measurementId: 'G-VKPCHGH296',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGQa2YvUwEB_1k7bBCs5YSGlT9lUOQl8',
    appId: '1:651530704617:android:67c0187e77ff4b16bc4278',
    messagingSenderId: '651530704617',
    projectId: 'mikrotaps',
    storageBucket: 'mikrotaps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD44dEwqhj_u_jzFLvM8atws66HkYY1Xuk',
    appId: '1:651530704617:ios:81c5d6ee68d68e78bc4278',
    messagingSenderId: '651530704617',
    projectId: 'mikrotaps',
    storageBucket: 'mikrotaps.firebasestorage.app',
    iosBundleId: 'com.example.mikrotap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD44dEwqhj_u_jzFLvM8atws66HkYY1Xuk',
    appId: '1:651530704617:ios:81c5d6ee68d68e78bc4278',
    messagingSenderId: '651530704617',
    projectId: 'mikrotaps',
    storageBucket: 'mikrotaps.firebasestorage.app',
    iosBundleId: 'com.example.mikrotap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlY5up6xTAdoEgYVk_vfBKwLteTQ8d7Jo',
    appId: '1:651530704617:web:58cb5f9fbfbd4fe0bc4278',
    messagingSenderId: '651530704617',
    projectId: 'mikrotaps',
    authDomain: 'mikrotaps.firebaseapp.com',
    storageBucket: 'mikrotaps.firebasestorage.app',
    measurementId: 'G-PFD6ZREJ9Z',
  );
}
